### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by rayking12** [od-c0d3r/highmount#1]

**Comment by rayking12** [comment]
in mobile version, in the school teachers section, the the text should be at right side of the photo

**Comment by o-rashad** [comment]
Good catch,

Actually, that was the design mockup, 
However, I contoured this issue during development and found that the text visibility will be none if I force it to be on the right side,
Therefore I made the text underneath,

let me know if you have any recommendations on how to approach the code.
Thank you for your contribution.
